const INITIAL_DISPLAY = "0";
const CALCULATION_ERROR = "MATH ERROR";
const DECIMAL_POINT = ".";
const MAX_DISPLAY_CHAR_LENGTH = 13;

export {
  INITIAL_DISPLAY,
  CALCULATION_ERROR,
  DECIMAL_POINT,
  MAX_DISPLAY_CHAR_LENGTH,
};
